[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.partitions = huge_app.csv
board_upload.flash_size = 4MB
board_build.psram = enabled

monitor_speed = 115200

; Upload settings for stability
upload_speed = 460800
upload_resetmethod = dtrdtr
upload_port = COM5

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  sensirion/Sensirion I2C SEN5X
  sensirion/Sensirion I2C SCD4x
  adafruit/Adafruit BME680 Library
  knolleary/PubSubClient
  bblanchon/ArduinoJson@^6.21.3
  bodmer/TFT_eSPI@^2.5.23
  https://github.com/tzapu/WiFiManager.git
  